source 'https://rubygems.org'

gem 'sinatra', '~> 4.2'
gem 'rack',    '~> 3.0'
gem 'webrick', '~> 1.9'
gem 'builder', '~> 3.2'
gem 'nokogiri', '~> 1.18'
gem 'sequel', '~> 5.86'
gem 'mysql2', '~> 0.5'